### ISSUE TITLE
[Bug] `-h` and `--help` exits with an error after the message

### ISSUE THREAD

**Issue by mtalexan** [garzj/google-photos-migrate#14]
If the `-h` or `--help` flag is used on the bases command, or any of the subcommands, it prints the help message correctly but then exits with an error.  The standard is to exit with success when help was specifically requested.  

A niche alternative is to print an error message about extraneous options/arguments/flags other than the `--help` and exit with an error.  But that's almost never used.

**Comment by lukehmcc** [comment]
This is a bug with `cmd-ts` https://github.com/Schniz/cmd-ts/pull/213
