### ISSUE TITLE
Output Question

### ISSUE THREAD

**Issue by janstadt** [garzj/google-photos-migrate#17]
I've successfully ran your tool on 1.16tb of google takeout photos (took 10hrs on my underpowered NAS but made it through). Can you help me understand the folder structure after everything is complete? Both AlbumsProcessed and PhotosProcessed seem to be close to the same size (~500gb a piece). Are these after deduplication scan? Do both directories have the same photos in them but is the photos directory just a flat directory and the albums directory has the same content but in their original directories? Id love to see a results.json file that lists all the stats once completed that explains things a bit. I need to know what directory i need to upload to immich and i dont want to do another dedupe scan. Any help would be great.

**Comment by garzj** [comment]
Your `PhotosProcessed` should now hold all the photos from the `Photos from *` folders, while `AlbumsProcessed` should contain the contents of the rest of the folders. There shouldn't be any duplicates between them except for the duplicates between the original takeout folders. Does this answer your question?

If unsure, you could run the tool again with the latest version as the structure was changed a bit. Now the albums are all inside `output/<album>` plus the merged `output/Photos`. Though I don't think this should be necessary.
