### ISSUE TITLE
EXIF Metadata other than DateTimeOriginal

### ISSUE THREAD

**Issue by middiu** [garzj/google-photos-migrate#20]
Hello there,

I was wondering if this tool takes care only of DateTimeOriginal metadata or if it fixes all the other metadata present in the JSON files.

I was doing some researches and it seems it is possible to fix GPS, Description and Tags metadata with the exittool options below.

I believe it shouldn't be too hard to implement these option here (if they are not implemented yet :) )

this is the link to the original article: https://legault.me/post/correctly-migrate-away-from-google-photos-to-icloud

````
exiftool -r -d %s -tagsfromfile "%d/%F.json" "-GPSAltitude<GeoDataAltitude" "-GPSLatitude<GeoDataLatitude" "-GPSLatitudeRef<GeoDataLatitude" "-GPSLongitude<GeoDataLongitude" "-GPSLongitudeRef<GeoDataLongitude" "-Keywords<Tags" "-Subject<Tags" "-Caption-Abstract<Description" "-ImageDescription<Description" "-DateTimeOriginal<PhotoTakenTimeTimestamp" -ext "*" -overwrite_original -progress --ext json <DirToProcess>
````

Thanks!

**Comment by garzj** [comment]
The tool only took care of several tags that populate DateTime values, so I added your tags.
I'm a little surprised though as at least in my takeout, all GPS data from a json file was also preserved inside its file's metadata.

**Comment by middiu** [comment]
that's great mate,  thanks a lot!
