### ISSUE TITLE
[Feature Request] Support .DNG format files

### ISSUE THREAD

**Issue by MeMyselfAndAI2023** [garzj/google-photos-migrate#21]
First of all: I love this project, it saved my life after using GoogleTakeout for GooglePhotos.

Could it support .DNG-files as well? Would be lovely ;)

I tried adding in /scr/config/extensions.ts
the following two settings (one after another)
a)
{ suffix: '.dng', metaType: MetaType.QUICKTIME },
b)
{ suffix: '.dng', metaType: MetaType.EXIF },

but both didn't work, it throws an error..? ("Error: File has invalid extension: xyz.DNG")

**Comment by garzj** [comment]
I added the same lines to the config and it seems like it should work.

Did you build the tool before running it or just use the npx version?

**Comment by MeMyselfAndAI2023** [comment]
I kinda cannot run a build version. I use Windows and have node and npm installed and did "npm install" and "npm run build".

When I run "node lib/index.js" nothing happens, no error or else..?

**Comment by garzj** [comment]
Look at the bottom of the README. You'll see that the entry file for the cli would be `lib/cli.js`, not `lib/index.js`. You already used the package.json scripts, why not just `npm start` instead?
Other than that, you should try yarn instead, so it'll pick up the lockfile.

**Comment by MeMyselfAndAI2023** [comment]
I am sorry for my stupid questions. I am just a noob to cli and all this and just trying to figure out how so transfer and safe my albums, after Google wants to increase costs for GoogleWorkspace storage 😪
When I run `npm start` it gives me back:
```
C:\CODINGSTUFF\google-photos-migrate-master>npm start --full

> google-photos-migrate@2.1.0 start
> node ./lib/cli.js

google-photos-migrate <subcommand>

where <subcommand> can be one of:

- full
- flat

```

What do I need to do? I tried "npm start --full" but didn't work. Sorry for bothering you and thanks for your replies.

**Comment by MeMyselfAndAI2023** [comment]
ChatGPT gave me ahint, so now I'm stuck here:
```

C:\CODINGSTUFF\google-photos-migrate-master>npm start full

> google-photos-migrate@2.1.0 start
> node ./lib/cli.js full

error: found 3 errors

  1. No value provided for input_dir
  2. No value provided for output_dir
  3. No value provided for error_dir

```

**Comment by garzj** [comment]
Most command line tools follow some form of the POSIX standard, so there are arguments, options and flags.
Running `npm start full --help`, you can see, these are arguments, so you can just add your paths in order and quote them if they contain spaces.

Windows example: `npm start full "C:\Users\...\path\to\Takeout\" .\output .\error`
