### ISSUE TITLE
[ISSUE] If Album title holds an Emji in its name, the script terminates

### ISSUE THREAD

**Issue by MeMyselfAndAI2023** [garzj/google-photos-migrate#22]
I had an Album-title like "Someone somewhere 🥰"

On Windows, the script crashes when trying to mkdir such a directory.

**Error-Output:**

> node:internal/fs/promises:769
>   return binding.mkdir(pathModule.toNamespacedPath(path),
>                  ^
> 
> Error: ENOENT: no such file or directory, mkdir
>     at mkdir (node:internal/fs/promises:769:18)
>     at _restructureAndProcess_1 (C:\Users\admin\AppData\Local\npm-cache\_npx\ab500ac20a79f2a5\node_modules\google-photos-migrate\lib\dir\restructure-and-process.js:47:48)
>     at _restructureAndProcess_1.next (<anonymous>)
>     at resume (C:\Users\admin\AppData\Local\npm-cache\_npx\ab500ac20a79f2a5\node_modules\google-photos-migrate\lib\dir\restructure-and-process.js:20:44)
>     at fulfill (C:\Users\admin\AppData\Local\npm-cache\_npx\ab500ac20a79f2a5\node_modules\google-photos-migrate\lib\dir\restructure-and-process.js:22:31) {
>   errno: -4058,
>   code: 'ENOENT',
>   syscall: 'mkdir'
> }
> 
> Node.js v20.9.0

How could that be fixed?

**Comment by garzj** [comment]
Seems like it's [this issue](https://github.com/nodejs/node/issues/48673), so downgrading to Node version <= v20.3.1 should fix it.

I recommend [nvm](https://github.com/coreybutler/nvm-windows) for Windows: `nvm use 20.3.1`.
