### ISSUE TITLE
[ISSUE] Album empty, though it should have pictures

### ISSUE THREAD

**Issue by MeMyselfAndAI2023** [garzj/google-photos-migrate#23]
After completing the run via npx-Version twice, I find the following confusing thing happens:
There are many album-folders that do not contain any pictures. Neither in "output" nor in "error", the folders are empty. Although those Albums in GooglePhotos contain pictures and I made a full Takeout of all folders via GoogleTakeout...?

Additional Info: The Pics themselves are there in the Takeout-folder, e.g.
P1060024.jpg and P1060024.jpg.json

**Comment by MeMyselfAndAI2023** [comment]
I re-checked and found that 34(!!) of 287 Album-folders generated in the output-Folder are empty!😱
Although all those pics and according jsons have been in the takeout and are also in output/Photos. What is going wrong here, what can I do?

**Comment by garzj** [comment]
Hm, hard to debug if I can't reproduce it.

What happens if you run the flat migration on one of the failed albums?

**Comment by MeMyselfAndAI2023** [comment]
Thanks for the reply. I see now, that one of those folder in question already have only json-files in it, no jpg. Maybe Google did something wrong in creating the takeout? 
![image](https://github.com/garzj/google-photos-migrate/assets/126958707/c10a4101-5674-4578-b12b-4d4e31a2a655)
The pics themselves are there, in Takeout, in other Albums and also they are in the "Photos"-folder of the full migration, but not in the migrated albums...?

**Comment by MeMyselfAndAI2023** [comment]
I think I found a solution. If I make a new takeout of only the albums that have been empty after migration, then they include the jpgs. So I will migrate and add them like this one by one I guess.
