### ISSUE TITLE
Error: Failed to find Google Photos directory in folder

### ISSUE THREAD

**Issue by a-elkaim** [garzj/google-photos-migrate#24]
Hello,

I have installed NodeJS & Yarn as per the instructions on my windows machine, but when launching the following command:

`npx google-photos-migrate@latest full 'G:\GoogleTakeout\Takeout\' 'G:\GoogleTakeout\output\' 'G:\GoogleTakeout\error\' --timeout 60000`

I get the following error:

`Error: Failed to find Google Photos directory in folder: G:\GoogleTakeout\Takeout\`

However there IS a "Google Photos" directory in "G:\GoogleTakeout\Takeout\", I'm not sure what is going on here.

**Comment by garzj** [comment]
On Windows, try using double instead of single quotes, otherwise they'll be included in the argument.

I'm not quite sure though because of the path in the error message.
