### ISSUE TITLE
End of processing at large atom (LargeFileSupport not enabled)

### ISSUE THREAD

**Issue by iCheater** [garzj/google-photos-migrate#29]
Hi! Is there any way to fix it? 

Started migration.
Processing photos...
Error: ExifTool failed to modify file:  /error/Photos/VID_20200316_141242.mp4
Reason: End of processing at large atom (LargeFileSupport not enabled) - /output/Photos/VID_20200316_141242.mp4

**Comment by garzj** [comment]
I made a [new branch](https://github.com/garzj/google-photos-migrate/tree/large-file-support) where I enabled ExifTools large file support. Can you try that?

**Comment by iCheater** [comment]
Works perfectly now, thx! 

Btw, you should add extra info to readme file about "how to build". Its complicated for "non web dev world"

**Comment by garzj** [comment]
There were some instructions at the bottom of the README, I added a TOC now to make them more clear.
Thanks for testing, I'll publish the changes.
