### ISSUE TITLE
0 files migrated

### ISSUE THREAD

**Issue by alternativesurfer** [garzj/google-photos-migrate#30]
Hi, I have a full google takeout directory with a significant number of files.
Just ran this and it moved 0 files, also 0 failures.

npx google-photos-migrate@latest full "\\10.0.0.65\media\gp-bak" "\\10.0.0.65\media\output" "\\10.0.0.65\media\error" --timeout 60000

![image](https://github.com/garzj/google-photos-migrate/assets/10135929/1387b5d6-780f-41ae-872f-a7dd7e317309)

**Comment by garzj** [comment]
How does the directory structure of your `gp-bak` look like?

Is it the similar to [this issue](https://github.com/garzj/google-photos-migrate/issues/23#issuecomment-1817524932)?

**Comment by alternativesurfer** [comment]
.\gp-bak\Google Photos\
With the various album folders and such underneath that.
![image](https://github.com/garzj/google-photos-migrate/assets/10135929/72265dc5-e1d4-4f1a-a9c4-ae553fc77247)

I don't think its related to that issue, I can see jpg/png/video files all present in the source folders.

**Comment by garzj** [comment]
I made a [new branch](https://github.com/garzj/google-photos-migrate/tree/no-files-fix) with some changes. Can you try them?

If they don't fix it, it would be interesting if the flat migration works as expected.

**Comment by alternativesurfer** [comment]
Ty!
Updated, no change in behavior.
![image](https://github.com/garzj/google-photos-migrate/assets/10135929/96452418-b6d9-4c1a-9e7a-9388a54c243b)


Tested flat, it appears to work
![image](https://github.com/garzj/google-photos-migrate/assets/10135929/734007ae-a54d-420d-b7b5-925700d4b21f)

**Comment by garzj** [comment]
I hope the flat migration was sufficient for you, but as for keeping the album structure, I can't spot the issue. I went ahead and added a verbose flag `-v`.

Would you try again with these instructions and post any useful output?
```powershell
cd google-photos-migrate
git pull origin no-files-fix --ff-only
git checkout no-files-fix
yarn deploy full "\\10.0.0.65\media\gp-bak" "\\10.0.0.65\media\output" "\\10.0.0.65\media\error" --timeout 60000
```

It could also be an issue with the network drive. What if you try it locally?

**Comment by alternativesurfer** [comment]
It looks like running it on a local directory (or mapping the share to a drive letter) solved it!
Thank you so much!

**Comment by garzj** [comment]
I tried this for myself now and it seems like my latest changes indeed fixed this issue. (The module node-glob didn't like the backslashes as path seperators.) I'll make a new release.
