### ISSUE TITLE
Discussion: Migrating is Copy or Move?

### ISSUE THREAD

**Issue by alternativesurfer** [garzj/google-photos-migrate#32]
Does this tool Copy or Move files to the new location?
And, is there a flag to modify that?

I have had to restart my migration a couple times and I swear I keep seeing the same file names appear in the CLI as it runs and I don't have enough free space to manage a 5TB takeout if its copying the files.

**Comment by garzj** [comment]
This tool does not modify your Google Takeout directory at all. It holds the paths to the restructured destination folders in memory and patches the files using ExifTool while copying them over as it runs.
Also, its progress is not tracked across restarts, so if you rerun the migration, it starts from the beginning.

Currently, there is no flag to change these behaviours, but it might not be that hard to implement one. I think an easy way would be to:
- copy each file to a temporary directory (maybe use the current error dir) and leave the original as a backup in case ExifTool fails
- modify it using ExifTool
- on success, move the file to the output folder and delete the original one from the Takeout folder
- on error, delete the temporary file and leave the original in the Takeout folder

This would track the progress by default, but it comes with a lot more risk. Even automated code tests for this repository may not catch every bug, especially if ExifTool does something weird during migration.

The general recommendation is to create a backup either way and check your results, so you might be better off running the flat migration album per album. But if you know some TypeScript you can of course try and give this a shot (?).

**Comment by alternativesurfer** [comment]
Thank you!
