### ISSUE TITLE
Error: ENOENT: no such file or directory, lstat

### ISSUE THREAD

**Issue by alternativesurfer** [garzj/google-photos-migrate#33]
migration stopping error:

```
[Error: ENOENT: no such file or directory, lstat 'K:\photos\historical-google\Photos\VID_20200822_160304.mp4'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'lstat',
  path: 'K:\\photos\\historical-google\\Photos\\VID_20200822_160304.mp4'
}

```

It ran through about 80% of the files before this triggered.

running command with:
npx google-photos-migrate@latest full "K:\gp-bak\test" "K:\photos\historical-google" "K:\gp-bak\error" --timeout 60000 -f

**Comment by garzj** [comment]
Did you solve this by now? I didn't have much time to look into this yet, but it seems hard to reproduce.
