### ISSUE TITLE
Infinitely creates "duplicates-*" directories.

### ISSUE THREAD

**Issue by claabs** [garzj/google-photos-migrate#36]
I'm running using the docker image on a takeout created today. On both full and flat mode, after processing about 4000 images, it starts creating millions of empty `duplicates-<number>` directories in the output directory until killed. Mine created about 5 million after a few minutes before I stopped it.

Haven't tested any other accounts, so not sure if it's due to just my takeout, or something else.

**Comment by claabs** [comment]
Nevermind, I'm an idiot. I thought I was pulling the image from a registry; forgot it was built locally. I was on an ancient version.

**Comment by claabs** [comment]
Actually, nevermind again. I'm seeing this issue even after building the latest Docker image.

**Comment by claabs** [comment]
I added some logging and it looks like the culprit is a file named `.jpg` with an accompanying `.json`.

**Comment by garzj** [comment]
Thanks for the debugging! The issue occured whenever the .json file reported an empty title. I added an option to rename empty filenames defaulting to `_`. Please let me know if this fixed it for you, so I can release a new version.

**Comment by claabs** [comment]
Yep, works for me now! Saw the log message:

`Sanitized file: /takeout/Google Photos/Photos from 2013/.jpg (New filename: _)`

Also, I created #37 as it was an issue I was experiencing when building the image. Figured you might want to fit that in before a release as well.

Thanks!
