### ISSUE TITLE
README for `fullMigrate` uses incorrect subcommands

### ISSUE THREAD

**Issue by mtalexan** [garzj/google-photos-migrate#8]
In the README for the `full-migrate` branch, the `fullMigrate` and `folderMigrate` subcommands are swapped.  The arguments to them are correct, just the word(s) used for the subcommand are backwards.

**Comment by lukehmcc** [comment]
My bad. This will be fixed when #11 is merged.

**Comment by mtalexan** [comment]
Ah, I put a fix for it in #15 as well since I was already touching the README.
