### ISSUE TITLE
[Feature Request] Support .MP format files

### ISSUE THREAD

**Issue by mtalexan** [garzj/google-photos-migrate#9]
Per a discussion on Photoprism (https://github.com/photoprism/photoprism/issues/1501), Google started generating `.MP` files for their "Live Photo" equivalent on Pixel devices.  This seems to replace the `.MVIMG` extension they used to use.  

The "solution" seems to be that the files just need a `.mp4` extension added to them (i.e. `.MP.mp4`).  To add confusion however, the files with the `.MP` extension are expected to match the basename of a JPEG file.  Google apparently has been embedding short MP4 video files into the metadata of the JPEG files, but then also creates a "sidecar" video file with the same content that they give the `.MP` extension to.  

I would propose a processing flag that would optionally add the `.mp4` extension to the `.MP` files, and would use the same sidecar JSON file as the JPEG (the json file will match the JPEG file name, not the `.MP` file's name) to modify the `.MP.mp4` file's metadata.

**Comment by garzj** [comment]
I created and linked a new branch, where I added the extension to the config file.
ExifTool will probably detect if the file looks like a mp4 and it will change the final file extension.
Please let me know if the changes work for you

**Comment by mtalexan** [comment]
That takes care of part of it, but its metadata should also be updated from the associated JSON file as well.  
Sometimes the JSON might be named `my_image.jpg.json` and it needs to update metadata for both `my_image.jpg` and `my_image.mp`/`my_image.mp.mp4`.

**Comment by garzj** [comment]
It should already do that, doesn't it?

**Comment by mtalexan** [comment]
> It should already do that, doesn't it?

Currently it completely ignores the files other than to indicate it's an unsupported extension. I don't find it in the processed output at all, so I presume it doesn't change the metadata either

**Comment by garzj** [comment]
I finally had some time and changed a bit on the linked branch, so what about now? Hope you can still make use of it
